// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0PkQo2mIf0E3vIOtx-kATy4zkigzpnOE',
    appId: '1:655728394377:web:d401369d944c3920568658',
    messagingSenderId: '655728394377',
    projectId: 'amanshu-notes',
    authDomain: 'amanshu-notes.firebaseapp.com',
    storageBucket: 'amanshu-notes.appspot.com',
    measurementId: 'G-JS8YBRB6SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZk0kmUESFQ8nDaPAoj2do6P3z1VfIysM',
    appId: '1:655728394377:android:d671ac120ed08404568658',
    messagingSenderId: '655728394377',
    projectId: 'amanshu-notes',
    storageBucket: 'amanshu-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaS1P3DLKy-jUlHlphyjjI5AORCyU_dTU',
    appId: '1:655728394377:ios:97973e8b90785596568658',
    messagingSenderId: '655728394377',
    projectId: 'amanshu-notes',
    storageBucket: 'amanshu-notes.appspot.com',
    iosClientId: '655728394377-9lajhodqu0f9speq3aps814a98ees4f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaS1P3DLKy-jUlHlphyjjI5AORCyU_dTU',
    appId: '1:655728394377:ios:97973e8b90785596568658',
    messagingSenderId: '655728394377',
    projectId: 'amanshu-notes',
    storageBucket: 'amanshu-notes.appspot.com',
    iosClientId: '655728394377-9lajhodqu0f9speq3aps814a98ees4f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
